### ISSUE TITLE
Error on /sentry help

### ISSUE THREAD

**Issue by enterih** [Jabelpeeps/Sentries#4]
`24.11 22:35:06 [Server] ERROR null
24.11 22:35:06 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'sentry' in plugin Sentries v2.0.4(build-b90)
24.11 22:35:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358) [spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193) [spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
24.11 22:35:06 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
24.11 22:35:06 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
24.11 22:35:06 [Server] INFO Caused by: java.lang.IllegalArgumentException: Permission name cannot be null
24.11 22:35:06 [Server] INFO at org.bukkit.permissions.PermissibleBase.isPermissionSet(PermissibleBase.java:50) ~[spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:135) ~[?:?]
24.11 22:35:06 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:109) ~[spigot1102fix.jar:git-Spigot-de459a2-51263e9]
24.11 22:35:06 [Server] INFO at org.jabelpeeps.sentries.CommandHandler.onCommand(CommandHandler.java:194) ~[?:?]
24.11 22:35:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot1102fix.jar:git-Spigot-de459a2-51263e9]`

I'm using the newest 1.10 Spigotbuild, Java 8 and the newest Citizens build.

**Comment by Jabelpeeps** [comment]
Odd, I've never seen errors on that command before, and I've used that one a lot.

Can you give a few more details on what you were doing when you got the error?

For example, were you on the console, or in-game? Were you op'ed or not? Did you give yourself the expected permissions?

**Comment by enterih** [comment]
I only use /sentry help and one command will be displayed: /sentry armour
At the new line comes an error occoured.

I use Permissionsex and use "*" perm

Whatever when,who and where i'm doing this command. The error is the same.

**Comment by Jabelpeeps** [comment]
"I only use /sentry help and one command will be displayed: /sentry armour"

This comment helped me find the bug, for some reason the perms on the next command in the list "arrowrate" was set to null, but I have now fixed that.  I guess PeX is stricter about such things than the perms plugin I use.

Let me know if the next version fixes it. (should be on the jenkins server soon)

**Comment by mcmonkey4eva** [comment]
@Sprungente Heads up, Sentinel is the *official* replacement for Sentry, not this. https://www.spigotmc.org/resources/sentinel.22017/
It's also much better quality!
(He spammed my repo, I'll spam his :P )

**Comment by enterih** [comment]
mcmonkey on sentinel i miss a lot of sentryfunctions and i don't understand why Sentry will stopped. This plugin continue Sentry and give me all what i need

PS: Jabelpeeps it's fixed. Thanks

**Comment by enterih** [comment]
mcmonkey and Jabelpeeps why you don't work as a team. Sentrinel 2.0 xD

What I will say: alone anyone from you are a good developer but in a team, i think you will be amazing

**Comment by Jabelpeeps** [comment]
@Sprungente Thanks for confirming this is fixed - marking as closed.

**Comment by mcmonkey4eva** [comment]
@Sprungente That's actually not a bad idea, and I would happily allow @Jabelpeeps to send in commits to the official Citizens combat plugin, Sentinel.

**Comment by Jabelpeeps** [comment]
@mcmonkey4eva I think you know why this isn't going to happen;  and who is spamming now?
