### ISSUE TITLE
ProjectileHitEvent

### ISSUE THREAD

**Issue by enterih** [Jabelpeeps/Sentries#6]
`25.11 17:13:46 [Server] ERROR Could not pass event ProjectileHitEvent to Sentries v2.0.4(build-b91)
25.11 17:13:46 [Server] INFO org.bukkit.event.EventException
25.11 17:13:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:783) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at net.minecraft.server.v1_11_R1.EntityProjectile.A_(EntityProjectile.java:170) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1652) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at net.minecraft.server.v1_11_R1.World.g(World.java:1627) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1453) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:635) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
25.11 17:13:46 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_11_R1.projectiles.CraftBlockProjectileSource cannot be cast to org.bukkit.entity.Entity
25.11 17:13:46 [Server] INFO at org.jabelpeeps.sentries.SentryListener.projectilehit(SentryListener.java:138) ~[?:?]
25.11 17:13:46 [Server] INFO at sun.reflect.GeneratedMethodAccessor491.invoke(Unknown Source) ~[?:?]
25.11 17:13:46 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
25.11 17:13:46 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
25.11 17:13:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1110.jar:git-Spigot-31fef09-78c7614]
25.11 17:13:46 [Server] INFO ... 14 more`

**Comment by Jabelpeeps** [comment]
Hi,

It would be helpful if you could say something about what you were doing when the stack trace you have posted was generated. 

Also it looks like you are running spigot 1.11, which I will certainly be working to support in the near future, however current Sentries is compiled against spigot 1.10.2.  Is it possible for you to repeat whatever produced the error whilst running 1.10.2?   It would be helpful to know if it still occurs.

Many thanks

**Comment by Jabelpeeps** [comment]
@Sprungente 
I can't look into this error without some more information about how it happened.  I'll leave this issue open for a little while longer, in case you are busy...

**Comment by enterih** [comment]
Sorry i forget to update it.

I started a testserver and tested on 1.11 and 1.10 

I can't reproduce the error. I had attacked and fight with some npc's. But the error is here (I think i saw he yesterday).

On the Testserver I found a bug. NPC's with bows don't attack with the bow. It's running to me and hit me with his hand.  This bug is on 1.10 and 1,11

Sometimes the KI isn't intelligent. It's hit me after 3 Seconds and then every second. (Can I change Attackspeed for close combat?)


Sentries Build 97 
Spigot 1.11 Latest Version
Spigot 1.10 Latest Version for 1.10

**Comment by Jabelpeeps** [comment]
> On the Testserver I found a bug. NPC's with bows don't attack with the bow. It's running to me and hit me with his hand. This bug is on 1.10 and 1,11

That's odd, I don't think I've seen that before.  I'm curious, did you use the '/sentry equip' command, or the citizens '/npc equip' command to give the bow to the NPC?

**Comment by Jabelpeeps** [comment]
Can you check whether the same happens with '/sentry equip'? 

If it works, I can look into fixing the /npc command, but using the /sentry one can be the workaround.

**Comment by enterih** [comment]
With sentry equip it will shot
